clear;
x = -12 : 0.1 : 12;
y = -12 : 0.1 : 12;
for i = 1 : length(x);
    for j = 1 : length(x);
        z(i, j) = exp(-((x(i)^2 + y(j)^2).^0.5 - 9).^2);
%         * exp(1i * x(i) + 1i * y(i));
%         z(i, j) = double((real(z(i, j))^2 + imag(z(i, j))^2)^0.5);
    end;
end;
mesh(x, y, z);